// Articles types
export const SET_ARTICLES = 'SET_ARTICLES';
export const SET_DISEASE_ARTICLES = 'SET_DISEASE_ARTICLES';
export const SET_CHOSEN_DISEASE = 'SET_CHOSEN_DISEASE';
export const ADD_DISEASE_ARTICLES = 'ADD_DISEASE_ARTICLES';
export const SET_ARTICLES_COUNT = 'SET_ARTICLES_COUNT';
export const LIKE_ARTICLE_ERROR = 'LIKE_ARTICLE_ERROR';
export const ADD_COMMENT_ARTICLE_ERROR = 'ADD_COMMENT_ARTICLE_ERROR';
export const SET_IS_LIKE_ARTICLE_ERROR_RAISE = 'SET_IS_LIKE_ARTICLE_ERROR_RAISE';
export const SET_IS_ADD_COMMENT_ARTICLE_ERROR_RAISE = 'SET_IS_ADD_COMMENT_ARTICLE_ERROR_RAISE';
export const SET_SELECTED_ARTICLE = 'SET_SELECTED_ARTICLE';
export const CLEAR_SELECTED_ARTICLE = 'CLEAR_SELECTED_ARTICLE';

// Diseases types
export const SET_DISEASES = 'SET_DISEASES';

// Theme types
export const SET_DARK_THEME = 'SET_DARK_THEME';

// Auth types
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
